GET http://localhost:8080/admin/metrics
###
POST http://localhost:8080/admin/reset
###
GET http://localhost:8080/app
###
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{"body": "I had something interesting for breakfast!"}